name=SharpSensor
version=1.0.0
author=YourFriendName
maintainer=YourFriendName <email@example.com>
sentence=A simple library for Sharp Infrared distance sensors.
paragraph=Supports various Sharp sensor models. Includes built-in averaging, calibration, and support for multiple units (cm, mm, inch).
category=Sensors
url=https://github.com/glebshow23-crypto/SharpSensor
architectures=*
